# Generated by Django 5.0.6 on 2025-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
